### ISSUE TITLE
TDWG 2024 abstract

### ISSUE THREAD

**Issue by dagendresen** [tdwg/expeditions#1]
# Abstract for TDWG 2024
Submission deadline 19th April 2024

**Comment by ben-norton** [comment]
The abstract deadline for TDWG 2024 expired on April 19th. Maybe you meant 2025?

**Comment by dagendresen** [comment]
We just now had the online task group meeting and chose this as an example of an issue to demonstrate what an issue can be.

**Comment by dagendresen** [comment]
Apropos @ben-norton are you interested and available to join the [expeditions task group](https://www.tdwg.org/community/cd/expeditions/)? We would love to welcome you to join us! Now initially we have had online bi-weekly task group meetings on Thursdays at 17:00 CEST = 11:00 AM in Raleigh, NC, USA.

**Comment by ben-norton** [comment]
> We just now had the online task group meeting and chose this as an example of an issue to demonstrate what an issue can be.

lol. My Fault.

**Comment by ben-norton** [comment]
> Apropos @ben-norton are you interested and available to join the [expeditions task group](https://www.tdwg.org/community/cd/expeditions/)? We would love to welcome you to join us! Now initially we have had online bi-weekly task group meetings on Thursdays at 17:00 CEST = 11:00 AM in Raleigh, NC, USA.

Sure.
